# Generated by Django 3.2.3 on 2021-08-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210814_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='start_date',
            field=models.DateField(default='2021-08-08', editable=False),
        ),
    ]
