# Generated by Django 3.2.3 on 2021-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_polls_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='start_date',
            field=models.DateField(default='2021-08-08'),
        ),
    ]
