# Generated by Django 3.2.3 on 2021-08-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_question_poll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poll',
            new_name='poll_name',
        ),
    ]
