# Generated by Django 3.2.3 on 2021-08-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_poll_question_poll_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
    ]
