# Generated by Django 3.2.3 on 2021-08-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210814_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='title',
            new_name='poll_title',
        ),
        migrations.AlterField(
            model_name='question',
            name='poll_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='polls.poll'),
        ),
    ]
