# Generated by Django 3.2.3 on 2021-08-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210814_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='poll_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll'),
        ),
    ]
