# Generated by Django 3.2.3 on 2021-08-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_question_poll_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='questions',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
